# Makefile for the attendance program

CXX = g++
CXXFLAGS = -std=c++11 -Wall
TARGET = lab13
SRC = lab13.cpp
all: $(TARGET)
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
